### PR TITLE
A client MUST NOT send a message body in a TRACE request

### PR DESCRIPTION
**Pull request by kachayev**
Due to [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.8) body should be omitted with `TRACE` request.

### CODE REVIEW

**Comment by ztellman** [comment]
This has a conflict with the multipart PR.

**Comment by ztellman** [comment]
Ok, #401 is merged.

**Comment by kachayev** [comment]
@ztellman Updated.

**Comment by kachayev** [comment]
After this one is merged I will update https://github.com/ztellman/aleph/pull/364 and https://github.com/ztellman/aleph/pull/406.

**Pull request merged**
