### PR TITLE
Support :multipart in HTTP clients requests

### PR DESCRIPTION
**Pull request by kachayev**
@ztellman Covering issue: https://github.com/ztellman/aleph/issues/159

Unit tests are included. 

API is slightly extended from the previous implementation to provided better compatibility with `clj-http` client.

### CODE REVIEW

**Comment by ztellman** [comment]
Thanks for pushing this over the finish line.

**Comment by royalaid** [comment]
Not sure if I am using it wrong but making a multipart call against httpbin.org doesn't seem to work. Adding the boundary by works for getting it to identify the files but the actual content never seems to propagate.

**Comment by kachayev** [comment]
@royalaid Would you please share the code that you're executing?

**Comment by royalaid** [comment]
Apologies for taking so long to respond, work got busy and had to set down my side project using this for a while, code is below:
```clojure
(http/post "http://httpbin.org/post" 
           {:multipart [{:content (java.io.File. "./test.jpg")}])})
```
I based it off the test cases that have been pushed with this PR. I would expect the return value to have files in the in the body.

**Comment by kachayev** [comment]
@royalaid Actually, I cannot reproduce this. Using `file.txt` from `tests`:

```clojure
user=> (-> (http/post "http://httpbin.org/post" {:multipart [{:content (java.io.File. "./test/file.txt")}]}) deref :body bs/to-string)
"{\n  \"args\": {}, \n  \"data\": \"--e5ff6b0d683514bc\\ncontent-disposition: form-data; name=\\\"file.txt\\\"; filename=\\\"file.txt\\\"\\ncontent-type: text/plain\\nthis is a file\\n\\n--e5ff6b0d683514bc--\", \n  \"files\": {}, \n  \"form\": {}, \n  \"headers\": {\n    \"Connection\": \"close\", \n    \"Content-Length\": \"149\", \n    \"Host\": \"httpbin.org\"\n  }, \n  \"json\": null, \n  \"origin\": \"194.44.212.15\", \n  \"url\": \"http://httpbin.org/post\"\n}\n"```

**Comment by royalaid** [comment]
The result should look like
```json
{
  "args": {},
  "data": "",
  "files": {},
  "form": {
    "file": "Users/Mark/Downloads/test.txt"
  },
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Content-Length": "168",
    "Content-Type": "multipart/form-data; boundary=------------------------d6179dc74eff1298",
    "Expect": "100-continue",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.51.0"
  },
  "json": null,
  "origin": "68.4.160.177",
  "url": "http://httpbin.org/post"
}
```
according to curl via `curl -v -X POST -F file=~/Downloads/test.txt http://httpbin.org/post`
Versus the result from aleph.multipart:

```json
{
  "args" : { },
  "data" : "--2ab91ebd5b1e45a1\ncontent-disposition: form-data; name=\"file.txt\"; filename=\"file.txt\"\ncontent-type: text/plain\nthis is a file\n\n--2ab91ebd5b1e45a1--",
  "files" : { },
  "form" : { },
  "headers" : {
    "Connection" : "close",
    "Content-Length" : "149",
    "Host" : "httpbin.org"
  },
  "json" : null,
  "origin" : "68.4.160.177",
  "url" : "http://httpbin.org/post"
}
```

**Comment by kachayev** [comment]
@royalaid Ah, actually you're right. It's not an issue by RFC, but most tools rely on "Content-Type" header which is not set here by `aleph` (and there's no easy way to set header manually as far random boundary generation is not visible for the user). Let me upgrade implementation slightly.

**Pull request merged**
