### PR TITLE
added body coercion copied from clj-http

### PR DESCRIPTION
**Pull request by shmish111**
Not sure how you feel about all this dynamic ns loading etc and how it fits in to what you want aleph to be but here it is, pretty much a copy and paste from clj-http.  It's what I and I guess a lot of others need.

### CODE REVIEW

**Comment by ztellman** [comment]
Yeah, this is pretty reasonable.  However, there are a lot of whitespace changes.  I just added `cljfmt` to the project, can you merge with my changes, and run `lein cljfmt` on yours?  Thanks.

**Comment by shmish111** [comment]
Is there anything else you would like me to do for this PR?

**Comment by shmish111** [comment]
Also, I'm using https://github.com/hozumi/clj-det-enc locally to detect the character encoding, would you mind if I added that here?  The issue being it's another dependency for the project...

**Comment by ztellman** [comment]
I'd prefer it be an optional dependency like the others, if possible.

**Comment by ztellman** [comment]
Actually, looking at that code, I'm not sure how it works with HTTP requests, since it'll consume the head of the InputStream.  Can you expand on how that would be used here?

**Comment by shmish111** [comment]
I've added the code to the PR.  It does mean you have to specify if you want an InputStream, rather than being the default.

**Comment by ztellman** [comment]
I'd honestly prefer it be left out.  If it belongs anywhere, it belongs in `byte-streams`.  Let me give it some thought.

**Comment by shmish111** [comment]
Indeed it would be nice in `bs/to-string`, I want that function to do as much for me as possible.  Would it adversely affect performance though?  If so it could be an option `:detect true`...  Also, I think I will change the default coercion to be none at all and require `:as :string` if you want a String.  What do you think?

**Comment by ztellman** [comment]
Yes, I'd prefer no coercion to be the default.

**Pull request merged**
