### PR TITLE
Handle WS handshake exceptions

### PR DESCRIPTION
**Pull request by shilder**
Handshake exceptions were silently ignored

### CODE REVIEW

**Comment by ztellman** [comment]
nice

**Comment by jaju** [comment]
Hi @ztellman - this fix is worthy of a release! I got hit by this too.
Are you planning a release of 0.4.7 anytime soon?

**Comment by kachayev** [comment]
@jaju This one is included into `0.4.7-alpha4` (released on Clojars already).

**Comment by jaju** [comment]
Thanks @kachayev - I'm already using that, but I meant to request that since this is now fixed and there doesn't seem to be any major open issue, the alpha could now move forward to beta/rc/release.

**Comment by kachayev** [comment]
Yeah... there are not that many open bugs right now, at least those we need to address urgently. There are a few that I personally would like to see merged before the release tho', like #430 and #432.

**Pull request merged**
