### PR TITLE
Expose max-queue-size setting for a connection-pool factory method

### PR DESCRIPTION
**Pull request by kachayev**
Right now `http/connection-pool` function creates `flow/instrumented-pool` with default `max-queue-size` (65536, which is pretty significant for a queue size).

### CODE REVIEW

**Comment by ztellman** [comment]
When the queue overflows, trying to make a call to `http/get` may throw a `RejectedExecutionException`.  Is that really the behavior you're looking for?

**Comment by kachayev** [comment]
@ztellman Correct. That's useful for example when implementing a proxy server with long-running requests to downstream: to have backpressure mechanism and not try to accept too many requests at the same time. Implementing any kind of a bounded queue/buffered stream as an additional layer seems like an unnecessary overhead as far as this part of thread pool functionality already.

**Comment by ztellman** [comment]
Okay, I have no objection to making this configurable, I just wanted to make sure this was actually a good solution to your problem.  I also have no objection to sub-typing `TimeoutException` to differentiate between the different timeout types.

**Comment by kachayev** [comment]
Cool! I'll implement `TimeoutException` sub-typing as a separate PR.

**Pull request merged**
